import { renderFormula } from "../formula.js";
import { createParabolaGraph } from "../graph/parabola-svg.js";
import "./lesson06.css";

const VIEWPORT = Object.freeze({ xMin: -6, xMax: 6, yMin: -8, yMax: 12, yTickStep: 2 });
const COLORS = Object.freeze({ curve: "#19735d", vertex: "#c88818" });
export const LESSON06_STEP_TITLES = Object.freeze(["Bridge In：两种形式", "教师示范：配方法", "互动配方：轮到你", "从数字到字母", "Axis & Vertex Formula", "双表示视图", "Quick Random Challenge", "Summary + Bridge Out"]);

function element(tag, className = "", text = "") { const node = document.createElement(tag); if (className) node.className = className; if (text) node.textContent = text; return node; }
function button(text, className = "lesson06-action") { const node = element("button", className, text); node.type = "button"; return node; }
function number(value) { return Number.isInteger(value) ? String(value) : String(Number(value.toFixed(4))); }
function signed(value) { return value === 0 ? "" : value > 0 ? "+" + number(value) : number(value); }
function vertexText({ a, h, k }) { const coefficient = a === 1 ? "" : a === -1 ? "-" : number(a); const inside = h === 0 ? "x" : "x" + (h > 0 ? "-" : "+") + number(Math.abs(h)); return "y=" + coefficient + "(" + inside + ")²" + signed(k); }
function generalText({ a, b, c }) { return "y=" + (a === 1 ? "" : a === -1 ? "-" : number(a)) + "x²" + (b === 0 ? "" : b > 0 ? "+" + number(b) + "x" : number(b) + "x") + signed(c); }
function formula(text, className = "lesson06-formula", dataset = "") { const node = element("div", className); if (dataset) node.dataset[dataset] = ""; renderFormula(node, text.replaceAll("²", "^2"), { ariaLabel: text, displayMode: true }); return node; }
function card(label, latex, ariaLabel, dataset) { const node = element("article", "lesson06-form-card"); const host = element("div", "lesson06-formula"); host.dataset[dataset] = ""; renderFormula(host, latex, { ariaLabel, displayMode: true }); node.append(element("p", "lesson06-card-label", label), host); return node; }

export function vertexFromGeneral({ a, b, c }) { if (![a, b, c].every(Number.isFinite) || a === 0) throw new TypeError("general form needs finite non-zero a"); const h = -b / (2 * a); return { a, h, k: (4 * a * c - b * b) / (4 * a) }; }

function createRoot(step) { const root = element("section", "lesson06-step"); const heading = element("header", "lesson06-heading"); heading.append(element("p", "lesson06-kicker", "LESSON 06 · " + String(step).padStart(2, "0") + " / 08"), element("h2", "lesson06-title", LESSON06_STEP_TITLES[step - 1])); root.append(heading); return root; }
function appendNavigation(root, step, onStepChange) { const nav = element("nav", "lesson06-step-controls"); nav.setAttribute("aria-label", "Lesson 6 步骤导航"); const previous = button("上一步", "lesson06-action lesson06-secondary"); previous.disabled = step === 1; previous.addEventListener("click", () => onStepChange(Math.max(1, step - 1))); const next = button(step === 8 ? "回到本课开始" : "下一步"); next.addEventListener("click", () => onStepChange(step === 8 ? 1 : step + 1)); nav.append(previous, element("span", "lesson06-step-count", step + " / 8"), next); root.append(nav); }
function addGraph(host, parameters, cleanup, ariaLabel) { const graph = createParabolaGraph(host, { viewport: VIEWPORT, curves: [{ ...parameters, color: COLORS.curve }], points: [{ x: parameters.h, y: parameters.k, color: COLORS.vertex, radius: 5 }], guides: [{ x: parameters.h, color: COLORS.vertex }], labels: [{ x: Math.min(5, parameters.h + .25), y: Math.min(11, parameters.k + .8), text: "V(" + number(parameters.h) + ", " + number(parameters.k) + ")" }], ariaLabel }); cleanup.push(() => graph.destroy()); return graph; }
function updateGraph(graph, p, ariaLabel) { graph.update({ curves: [{ ...p, color: COLORS.curve }], points: [{ x: p.h, y: p.k, color: COLORS.vertex, radius: 5 }], guides: [{ x: p.h, color: COLORS.vertex }], labels: [{ x: Math.min(5, p.h + .25), y: Math.min(11, p.k + .8), text: "V(" + number(p.h) + ", " + number(p.k) + ")" }], ariaLabel }); }
function reveal(text, dataset) { const node = button(text); node.dataset[dataset] = ""; return node; }

function renderBridge(root) { const forms = element("div", "lesson06-forms"); forms.append(card("顶点式 (vertex form)", "y=a(x-h)^2+k", "y=a(x-h)²+k", "lesson06VertexForm"), element("strong", "lesson06-arrow", "↔"), card("一般式 (general form)", "y=ax^2+bx+c", "y=ax²+bx+c", "lesson06GeneralForm")); const control = reveal("Reveal Connection", "lesson06BridgeReveal"); const conclusion = element("p", "lesson06-conclusion", "同一条抛物线可以用两种形式表示：一般式便于展开与代点；顶点式便于读顶点、对称轴和最值。"); conclusion.hidden = true; control.addEventListener("click", () => { conclusion.hidden = false; }); root.append(element("p", "lesson06-question", "同一条抛物线能否在两种形式之间转换？"), forms, control, conclusion); }

function renderDemo(root, _change, cleanup) { const moves = [["原式", "y=2x^2-8x+3"], ["提取 a", "y=2(x^2-4x)+3"], ["加减同一个数", "y=2[(x^2-4x+4)-4]+3"], ["合成完全平方", "y=2(x-2)^2-8+3"], ["整理成顶点式", "y=2(x-2)^2-5"]]; let index = 0; const morph = element("div", "lesson06-morph"); const status = element("p", "lesson06-status"); const next = button("Next Move"); next.dataset.lesson06DemoNext = ""; const result = element("div", "lesson06-demo-result"); result.dataset.lesson06DemoResult = ""; result.hidden = true; const graphPanel = element("div", "lesson06-graph-panel"); graphPanel.hidden = true; addGraph(graphPanel, { a: 2, h: 2, k: -5 }, cleanup, "y=2(x-2)²-5 的图象"); function render() { morph.replaceChildren(element("p", "lesson06-card-label", moves[index][0]), formula(moves[index][1], "lesson06-formula lesson06-morph-formula")); status.textContent = "第 " + (index + 1) + " / 5 步：" + moves[index][0] + "。"; const done = index === 4; result.hidden = !done; graphPanel.hidden = !done; next.disabled = done; if (done) result.textContent = "顶点 (vertex)：(2, -5)；对称轴 (axis of symmetry)：x=2。"; } next.addEventListener("click", () => { index = Math.min(4, index + 1); render(); }); root.append(element("p", "lesson06-question", "每次只做一个配方动作：先把二次项系数提出，再在括号内加减同一个数。"), morph, next, status, result, graphPanel); render(); }

function renderInteractive(root, _change, cleanup) { const choices = element("div", "lesson06-choice-grid"); const status = element("p", "lesson06-status", "先判断下一步，再 Reveal。 "); [["提出 2", "先得到 2(x²+4x)+5。"], ["加减 4", "在括号内配成 (x+2)²。"], ["直接读顶点", "必须先改写成顶点式。"]].forEach(([text, feedback]) => { const choice = button(text, "lesson06-action lesson06-secondary"); choice.dataset.lesson06InteractiveChoice = ""; choice.addEventListener("click", () => { status.textContent = "已记录：" + feedback + "答案将在 Reveal 后展示。"; }); choices.append(choice); }); const answer = element("div", "lesson06-answer"); answer.dataset.lesson06InteractiveAnswer = ""; answer.hidden = true; const graphPanel = element("div", "lesson06-graph-panel"); graphPanel.hidden = true; addGraph(graphPanel, { a: 2, h: -2, k: -3 }, cleanup, "y=2(x+2)²-3 的图象"); const control = reveal("Reveal Answer", "lesson06InteractiveReveal"); control.addEventListener("click", () => { answer.replaceChildren(formula("y=2(x^2+4x)+5"), formula("y=2[(x+2)^2-4]+5"), formula("y=2(x+2)^2-3"), element("p", "", "所以 h=-2；顶点 (vertex) 是 (-2, -3)，对称轴 (axis of symmetry) 是 x=-2。")); answer.hidden = false; graphPanel.hidden = false; }); root.append(element("p", "lesson06-question", "把 y=2x²+8x+5 改写成顶点式。注意：(x+2)² 对应 h=-2。"), formula("y=2x^2+8x+5", "lesson06-formula lesson06-hero"), choices, status, control, answer, graphPanel); }

function renderSymbolic(root) { const moves = [["一般式", "y=ax^2+bx+c"], ["提出 a", "y=a(x^2+\\frac{b}{a}x)+c"], ["在括号内配方", "y=a[(x+\\frac{b}{2a})^2-\\frac{b^2}{4a^2}]+c"], ["整理", "y=a(x+\\frac{b}{2a})^2+\\frac{4ac-b^2}{4a}"], ["与顶点式对齐", "y=a[x-(-\\frac{b}{2a})]^2+\\frac{4ac-b^2}{4a}"]]; let index = 0; const morph = element("div", "lesson06-morph"); const next = button("Next Move"); next.dataset.lesson06SymbolicNext = ""; function render() { morph.replaceChildren(element("p", "lesson06-card-label", moves[index][0]), formula(moves[index][1], "lesson06-formula lesson06-morph-formula")); next.disabled = index === 4; } next.addEventListener("click", () => { index = Math.min(4, index + 1); render(); }); root.append(element("p", "lesson06-question", "数字配方的每一步都可以推广到字母；最后把括号写成 x-h，公式来源就清楚了。"), morph, next); render(); }

function renderFormulaCards(root) { const cards = element("div", "lesson06-formula-cards"); cards.append(card("对称轴 (axis of symmetry)", "x=-\\frac{b}{2a}", "x=-b/(2a)", "lesson06AxisFormula"), card("顶点 (vertex)", "\\left(-\\frac{b}{2a},\\frac{4ac-b^2}{4a}\\right)", "(-b/(2a), (4ac-b²)/(4a))", "lesson06VertexFormula")); root.append(element("p", "lesson06-question", "这些公式不是孤立背诵的结论；它们来自刚才的配方过程。"), cards, element("p", "lesson06-conclusion", "配方 → 顶点式 → 对比 y=a(x-h)²+k：h=-b/(2a)，k=(4ac-b²)/(4a)。")); }

function renderDual(root, _change, cleanup) { const general = { a: 2, b: -8, c: 3 }; const vertex = vertexFromGeneral(general); const layout = element("div", "lesson06-dual-layout"); const comparison = element("div", "lesson06-comparison"); comparison.append(card("一般式 (general form)", "y=2x^2-8x+3", generalText(general), "lesson06DualGeneral"), card("顶点式 (vertex form)", "y=2(x-2)^2-5", vertexText(vertex), "lesson06DualVertex"), element("p", "lesson06-conclusion", "一般式便于展开/代点；顶点式便于读顶点、对称轴和最值。两式描述的是同一条抛物线。")); const graphPanel = element("div", "lesson06-graph-panel"); addGraph(graphPanel, vertex, cleanup, "一般式与顶点式表示的同一条抛物线"); layout.append(comparison, graphPanel); root.append(layout); }

function choose(values, random) { return values[Math.min(values.length - 1, Math.floor(Math.max(0, Math.min(.999999, Number(random()) || 0)) * values.length))]; }
function makeChallenge(random) { const vertex = { a: choose([1, 2, -1], random), h: choose([-3, -2, -1, 1, 2, 3], random), k: choose([-3, -2, -1, 1, 2, 3], random) }; return { vertex, general: { a: vertex.a, b: -2 * vertex.a * vertex.h, c: vertex.a * vertex.h * vertex.h + vertex.k } }; }
function renderChallenge(root, _change, cleanup, random) { const prompt = element("div", "lesson06-question"); const answer = element("div", "lesson06-answer"); answer.dataset.lesson06ChallengeAnswer = ""; answer.hidden = true; const graphPanel = element("div", "lesson06-graph-panel"); graphPanel.hidden = true; const graph = addGraph(graphPanel, { a: 1, h: 0, k: 0 }, cleanup, "随机挑战图象"); const control = reveal("Reveal Answer", "lesson06ChallengeReveal"); const next = button("New Challenge", "lesson06-action lesson06-secondary"); let challenge; function render() { challenge = makeChallenge(random); prompt.replaceChildren(element("span", "", "只给一般式："), formula(generalText(challenge.general), "lesson06-formula lesson06-hero"), element("span", "", "请口答对称轴与顶点。")); answer.hidden = true; graphPanel.hidden = true; } control.addEventListener("click", () => { answer.replaceChildren(formula(vertexText(challenge.vertex)), element("p", "", "对称轴 (axis of symmetry)：x=" + number(challenge.vertex.h) + "；顶点 (vertex)：(" + number(challenge.vertex.h) + ", " + number(challenge.vertex.k) + ")。")); answer.hidden = false; graphPanel.hidden = false; updateGraph(graph, challenge.vertex, vertexText(challenge.vertex) + " 的图象"); }); next.addEventListener("click", render); const actions = element("div", "lesson06-actions"); actions.append(control, next); root.append(element("p", "lesson06-prompt", "题目先从简单顶点式随机展开而来；只练习读对称轴和顶点，不做题库或计分。"), prompt, actions, answer, graphPanel); render(); }
function renderSummary(root) { const route = element("div", "lesson06-summary-route"); ["一般式 (general form)", "配方法 (completing the square)", "顶点式 (vertex form)", "顶点 / 对称轴"].forEach((label, index) => { route.append(element("strong", "lesson06-route-node", label)); if (index < 3) route.append(element("span", "lesson06-route-arrow", "→")); }); root.append(route, element("p", "lesson06-bridge-out", "Bridge Out：令 y=0，一般式 y=ax²+bx+c 会变成一元二次方程；下一课将研究它与 x 轴的交点。")); }

const RENDERERS = Object.freeze([renderBridge, renderDemo, renderInteractive, renderSymbolic, renderFormulaCards, renderDual, renderChallenge, renderSummary]);
export function renderLesson06(stage, { step = 1, onStepChange = () => {}, random = Math.random }) { const safeStep = Math.min(8, Math.max(1, Number(step) || 1)); const cleanup = []; const root = createRoot(safeStep); RENDERERS[safeStep - 1](root, onStepChange, cleanup, random); appendNavigation(root, safeStep, onStepChange); stage.replaceChildren(root); return { destroy() { cleanup.forEach((dispose) => dispose()); } }; }
