import { renderFormula } from "../formula.js";
import { createParabolaGraph } from "../graph/parabola-svg.js";
import "./lesson11.css";

export const LESSON11_STEP_TITLES = Object.freeze(["一座拱门，怎样用函数描述？", "Real → Math：先保留关键信息", "坐标系怎样建立最省事？", "选择合适的函数模型", "关键点决定抛物线", "代入关键点，求出解析式", "Arch Design Lab", "净空高度够吗？", "Random Practice：设计一座拱门"]);
const PRACTICE = Object.freeze([{ width: 6, height: 3 }, { width: 8, height: 4 }, { width: 10, height: 5 }, { width: 12, height: 3 }]);
function node(tag, className = "", text = "") { const item = document.createElement(tag); if (className) item.className = className; if (text) item.textContent = text; return item; }
function button(text, className = "lesson11-action") { const item = node("button", className, text); item.type = "button"; return item; }
function formula(latex, label, className = "lesson11-formula") { const item = node("div", className); renderFormula(item, latex, { ariaLabel: label, displayMode: true }); return item; }
function model(width, height) { return { width, height, half: width / 2, a: -4 * height / (width ** 2) }; }
function fraction(width, height) { let numerator = 4 * height; let denominator = width ** 2; let divisor = Math.min(numerator, denominator); while (divisor > 1 && (numerator % divisor !== 0 || denominator % divisor !== 0)) divisor -= 1; numerator /= divisor; denominator /= divisor; return numerator === 1 ? "-\\frac{1}{" + denominator + "}" : "-\\frac{" + numerator + "}{" + denominator + "}"; }
function latexFor(item) { return "y=" + fraction(item.width, item.height) + "x^2+" + item.height; }
function root(step) { const item = node("section", "lesson11-step"); const header = node("header", "lesson11-heading"); header.append(node("p", "lesson11-kicker", "LESSON 11 · " + String(step).padStart(2, "0") + " / 09"), node("h2", "lesson11-title", LESSON11_STEP_TITLES[step - 1])); item.append(header); return item; }
function navigation(rootElement, step, onStepChange) { const nav = node("nav", "lesson11-controls"); nav.setAttribute("aria-label", "Lesson 11 步骤导航"); const previous = button("上一步", "lesson11-action lesson11-secondary"); previous.disabled = step === 1; previous.addEventListener("click", () => onStepChange(Math.max(1, step - 1))); const next = button(step === 9 ? "回到本课开始" : "下一步"); next.addEventListener("click", () => onStepChange(step === 9 ? 1 : step + 1)); nav.append(previous, node("span", "lesson11-count", step + " / 9"), next); rootElement.append(nav); }
function createGraph(host, item) { return createParabolaGraph(host, { viewport: { xMin: -7, xMax: 7, yMin: -2, yMax: 8, xTickStep: 1, yTickStep: 1 }, curves: [{ a: item.a, h: 0, k: item.height, color: "#17634e" }], points: [{ x: -item.half, y: 0, color: "#d98935", radius: 6 }, { x: 0, y: item.height, color: "#7653af", radius: 6 }, { x: item.half, y: 0, color: "#d98935", radius: 6 }], guides: [{ x: 0, color: "#d98935" }], ariaLabel: "拱门抛物线，关键点与对称轴" }); }
function revealStep(rootElement, prompt, answerText) { const answer = node("p", "lesson11-reveal", answerText); answer.hidden = true; const reveal = button("Reveal：查看答案"); reveal.addEventListener("click", () => { answer.hidden = false; }); rootElement.append(node("p", "lesson11-prompt", prompt), reveal, answer); }
function renderOpening(rootElement) { revealStep(rootElement, "一座对称拱门跨度 8 m、最高点离地 4 m。我们要写出门洞上沿的函数解析式 (function equation)。", "Real → Math 的第一步：提取位置、对称和高度信息，而不是马上代公式。"); }
function renderRealMath(rootElement) { const rows = ["地面 → x 轴；高度 → y 坐标。", "左右对称 → 对称轴 (axis of symmetry) 经过拱门正中。", "跨度 8 m → 两端横坐标相距 8。", "最高点 4 m → 顶点 (vertex) 的纵坐标是 4。"].map((text) => { const row = node("p", "lesson11-reveal", text); row.hidden = true; rootElement.append(row); return row; }); let index = 0; const reveal = button("Reveal：一条对应关系"); reveal.addEventListener("click", () => { if (index < rows.length) rows[index++].hidden = false; }); rootElement.prepend(node("p", "lesson11-prompt", "把文字和图形中的信息翻译成数学对象。每次 Reveal 一条对应关系。")); rootElement.append(reveal); }
function renderCoordinates(rootElement, cleanup) { const item = model(8, 4); const panel = node("div", "lesson11-workbench"); panel.append(node("p", "lesson11-prompt", "把原点放在拱门中点的地面处，让 y 轴通过最高点；这样顶点横坐标就是 0。"), node("p", "lesson11-note", "关键点：左端 (-4,0)，顶点 (0,4)，右端 (4,0)。")); const layout = node("div", "lesson11-layout"); const graphPanel = node("div", "lesson11-graph-panel"); const host = node("div", "lesson11-graph-host"); graphPanel.append(host); layout.append(graphPanel, panel); rootElement.append(layout); const chart = createGraph(host, item); cleanup.push(() => chart.destroy()); }
function renderChoice(rootElement) { const answer = node("p", "lesson11-reveal"); answer.hidden = true; const vertex = button("y=a(x-h)²+k"); const general = button("y=ax²+bx+c", "lesson11-action lesson11-secondary"); vertex.addEventListener("click", () => { answer.hidden = false; answer.textContent = "正确：已知顶点时，顶点式 (vertex form) 最便于代入端点求参数。"; }); general.addEventListener("click", () => { answer.hidden = false; answer.textContent = "一般式也可以，但未知数更多；这里优先选顶点式。"; }); rootElement.append(node("p", "lesson11-prompt", "已知顶点在 (0,4)，抛物线开口向下。哪一种形式最便于代入端点求参数？"), node("div", "lesson11-actions")); rootElement.querySelector(".lesson11-actions").append(vertex, general); rootElement.append(answer); }
function renderPoints(rootElement) { revealStep(rootElement, "三个关键点足以把实际信息固定下来。先根据坐标系写点，再核对。", "关键点 (key points)：左端 (-4,0)，顶点 (0,4)，右端 (4,0)。由于左右对称，只需用一个端点代入。 "); }
function renderDerivation(rootElement) { const rows = [formula("0=a\\cdot4^2+4", "端点代入"), formula("a=-\\frac14", "a 等于负四分之一"), formula("y=-\\frac14x^2+4", "抛物线解析式")]; rows.forEach((item) => { item.hidden = true; rootElement.append(item); }); let index = 0; const reveal = button("Reveal：代入计算"); reveal.addEventListener("click", () => { if (index < rows.length) rows[index++].hidden = false; }); rootElement.prepend(node("p", "lesson11-prompt", "顶点式为 y=ax²+4。把右端点 (4,0) 代入，解出 a。")); rootElement.append(reveal); }
function renderLab(rootElement, cleanup) { let item = model(8, 4); const panel = node("div", "lesson11-workbench"); const width = document.createElement("input"); width.type = "range"; width.min = "6"; width.max = "12"; width.step = "2"; width.value = "8"; width.dataset.lesson11Width = ""; width.setAttribute("aria-label", "跨度 W（m）"); const height = document.createElement("input"); height.type = "range"; height.min = "3"; height.max = "6"; height.step = "1"; height.value = "4"; height.dataset.lesson11Height = ""; height.setAttribute("aria-label", "高度 H（m）"); const equation = formula(latexFor(item), "拱门解析式", "lesson11-formula lesson11-current"); const points = node("p", "lesson11-status"); points.dataset.lesson11KeyPoints = ""; const layout = node("div", "lesson11-layout"); const graphPanel = node("div", "lesson11-graph-panel"); const host = node("div", "lesson11-graph-host"); graphPanel.append(host); layout.append(graphPanel, panel); rootElement.append(layout); let chart = createGraph(host, item);
  function update() { item = model(Number(width.value), Number(height.value)); equation.replaceChildren(); renderFormula(equation, latexFor(item), { displayMode: true, ariaLabel: "跨度 " + item.width + " 米，高 " + item.height + " 米的拱门解析式" }); points.textContent = "关键点 (key points)：(" + -item.half + ", 0)、(0, " + item.height + ")、(" + item.half + ", 0)；对称轴 x=0。"; chart.update({ curves: [{ a: item.a, h: 0, k: item.height, color: "#17634e" }], points: [{ x: -item.half, y: 0, color: "#d98935", radius: 6 }, { x: 0, y: item.height, color: "#7653af", radius: 6 }, { x: item.half, y: 0, color: "#d98935", radius: 6 }] }); }
  const controls = node("div", "lesson11-range"); controls.append(node("label", "", "跨度 W（m）"), width, node("label", "", "高度 H（m）"), height); panel.append(node("p", "lesson11-prompt", "改变跨度 W 与高度 H：坐标、函数解析式和抛物线会同时更新。"), controls, equation, points); width.addEventListener("input", update); height.addEventListener("input", update); update(); cleanup.push(() => chart.destroy()); }
function renderClearance(rootElement) { revealStep(rootElement, "拱门模型 y=-1/4x²+4 中，离中线 2 m 处的高度是多少？把横向位置代入函数。", "y=-1/4·2²+4=3。因此离中线 2 m 处的净空高度为 3 m。 "); }
function renderPractice(rootElement, random) { let index = Math.min(PRACTICE.length - 1, Math.floor(Math.max(0, Math.min(.999, Number(random()) || 0)) * PRACTICE.length)); const prompt = node("p", "lesson11-question"); const answer = node("div", "lesson11-reveal"); answer.dataset.lesson11PracticeAnswer = ""; const reveal = button("Reveal：检查答案"); reveal.dataset.lesson11RevealPractice = ""; const next = button("New Practice", "lesson11-action lesson11-secondary"); function render() { const item = model(PRACTICE[index].width, PRACTICE[index].height); prompt.textContent = "一座对称拱门跨度 " + item.width + " m，最高点离地 " + item.height + " m。以中点地面为原点建立坐标系，求上沿抛物线的解析式。"; answer.replaceChildren(node("p", "", "关键点：(" + -item.half + ",0)、(0," + item.height + ")、(" + item.half + ",0)。"), formula(latexFor(item), "解析式")); answer.hidden = true; } reveal.addEventListener("click", () => { answer.hidden = false; }); next.addEventListener("click", () => { index = (index + 1) % PRACTICE.length; render(); }); rootElement.append(node("p", "lesson11-prompt", "按“建系 → 写关键点 → 选模型 → 求解析式”完成建模，答案默认隐藏。"), prompt, node("div", "lesson11-actions")); rootElement.querySelector(".lesson11-actions").append(next, reveal); rootElement.append(answer); render(); }
const RENDERERS = [renderOpening, renderRealMath, renderCoordinates, renderChoice, renderPoints, renderDerivation, renderLab, renderClearance, renderPractice];
export function renderLesson11(stage, { step = 1, onStepChange = () => {}, random = Math.random } = {}) { const safe = Math.min(9, Math.max(1, Number(step) || 1)); const cleanup = []; const item = root(safe); if (safe === 9) renderPractice(item, random); else RENDERERS[safe - 1](item, cleanup); navigation(item, safe, onStepChange); stage.replaceChildren(item); return { destroy() { cleanup.forEach((dispose) => dispose()); } }; }
