import { renderFormula } from "../formula.js";
import { createParabolaGraph } from "../graph/parabola-svg.js";
import "./lesson10.css";

export const LESSON10_STEP_TITLES = Object.freeze([
  "从降价问题开始", "把情境翻译成变量", "利润函数从哪里来？", "图象告诉我们最大值",
  "别忘了实际范围", "Profit Control Lab", "回到问题：如何达到目标？", "Random Practice：最大利润",
]);

const DATA = Object.freeze({ price: 60, cost: 30, sales: 40, gain: 2 });
const PRACTICE = Object.freeze([{ price: 50, cost: 26, sales: 30, gain: 2 }, { price: 60, cost: 30, sales: 40, gain: 2 }, { price: 70, cost: 35, sales: 50, gain: 3 }]);

function node(tag, className = "", text = "") { const item = document.createElement(tag); if (className) item.className = className; if (text) item.textContent = text; return item; }
function button(text, className = "lesson10-action") { const item = node("button", className, text); item.type = "button"; return item; }
function formula(latex, label, className = "lesson10-formula") { const item = node("div", className); renderFormula(item, latex, { ariaLabel: label, displayMode: true }); return item; }
function model(data, discount = 0) {
  const a = -data.gain; const b = data.gain * (data.price - data.cost) - data.sales; const c = data.sales * (data.price - data.cost);
  const best = -b / (2 * a); return { ...data, discount, a, b, c, best, maximum: a * best ** 2 + b * best + c, profit: (data.price - data.cost - discount) * (data.sales + data.gain * discount) };
}
function latexFor(item) { return "P(d)=" + item.a + "d^2" + (item.b >= 0 ? "+" : "") + item.b + "d+" + item.c; }
function root(step) { const item = node("section", "lesson10-step"); const header = node("header", "lesson10-heading"); header.append(node("p", "lesson10-kicker", "LESSON 10 · " + String(step).padStart(2, "0") + " / 08"), node("h2", "lesson10-title", LESSON10_STEP_TITLES[step - 1])); item.append(header); return item; }
function navigation(rootElement, step, onStepChange) { const nav = node("nav", "lesson10-controls"); nav.setAttribute("aria-label", "Lesson 10 步骤导航"); const previous = button("上一步", "lesson10-action lesson10-secondary"); previous.disabled = step === 1; previous.addEventListener("click", () => onStepChange(Math.max(1, step - 1))); const next = button(step === 8 ? "回到本课开始" : "下一步"); next.addEventListener("click", () => onStepChange(step === 8 ? 1 : step + 1)); nav.append(previous, node("span", "lesson10-count", step + " / 8"), next); rootElement.append(nav); }
function graph(host, item, point) { return createParabolaGraph(host, { viewport: { xMin: 0, xMax: 20, yMin: -2, yMax: 15, xTickStep: 2, yTickStep: 2 }, curves: [{ a: item.a / 100, h: item.best, k: item.maximum / 100, color: "#17634e" }], points: point ? [{ x: point.x, y: point.y / 100, color: "#d98935", radius: 6 }] : [{ x: item.best, y: item.maximum / 100, color: "#7653af", radius: 6 }], guides: [{ x: item.best, color: "#d98935" }], ariaLabel: "降价与日利润图象，纵轴单位为百元" }); }
function workbench(rootElement, content, graphOptions) { const layout = node("div", "lesson10-layout"); const panel = node("div", "lesson10-graph-panel"); const host = node("div", "lesson10-graph-host"); panel.append(host); layout.append(panel, content); rootElement.append(layout); return graphOptions(host); }

function renderOpening(rootElement) { const answer = node("p", "lesson10-reveal", "设每件降价 d 元。d 是自变量 (independent variable)，日利润 P 是因变量 (dependent variable)。"); answer.hidden = true; const reveal = button("Reveal：设未知数"); reveal.addEventListener("click", () => { answer.hidden = false; }); rootElement.append(node("p", "lesson10-prompt", "原售价 60 元、进价 30 元；每天卖 40 件。每降价 1 元，每天多卖 2 件。怎样找到最大日利润？"), node("p", "lesson10-question", "先口答：把“每件降价多少元”设为哪个变量？"), reveal, answer); }
function renderRelations(rootElement) { const rows = [formula("\\text{单件利润}=60-d-30=30-d", "单件利润等于 30 减 d"), formula("\\text{日销量}=40+2d", "日销量等于 40 加 2d")]; let shown = 0; rows.forEach((item) => { item.hidden = true; rootElement.append(item); }); const reveal = button("Reveal：数量关系"); reveal.addEventListener("click", () => { if (shown < rows.length) rows[shown++].hidden = false; }); rootElement.append(node("p", "lesson10-prompt", "变量 d 每增加 1，售价少 1 元、销量多 2 件。先写出两个随 d 变化的量。"), reveal); }
function renderBuild(rootElement) { const rows = [formula("P(d)=(30-d)(40+2d)", "总利润等于单件利润乘日销量"), formula("P(d)=-2d^2+20d+1200", "利润函数")]; let shown = 0; rows.forEach((item) => { item.hidden = true; rootElement.append(item); }); const reveal = button("Reveal：建立函数"); reveal.addEventListener("click", () => { if (shown < rows.length) rows[shown++].hidden = false; }); rootElement.append(node("p", "lesson10-prompt", "总利润 = 单件利润 × 日销量。先保留乘积，再展开成二次函数。"), reveal); }
function renderMaximum(rootElement, cleanup) { const item = model(DATA); const answer = node("p", "lesson10-reveal", "顶点 (vertex) 对应 d=5，最大日利润为 1250 元。图象纵轴以百元计，顶点纵坐标为 12.5。 "); answer.hidden = true; const reveal = button("Reveal：最大利润"); reveal.addEventListener("click", () => { answer.hidden = false; }); const panel = node("div", "lesson10-workbench"); panel.append(node("p", "lesson10-prompt", "P(d) 的图象是一条开口向下的抛物线 (parabola)。最高点对应最大日利润。"), formula(latexFor(item), "利润函数"), reveal, answer); const chart = workbench(rootElement, panel, (host) => graph(host, item)); cleanup.push(() => chart.destroy()); }
function renderDomain(rootElement) { const answer = formula("0\\le d\\le30", "d 大于等于零且小于等于三十", "lesson10-formula lesson10-reveal"); answer.hidden = true; const note = node("p", "lesson10-note", "最优值 d=5 在实际范围 (domain) 内，因此这个决策可行。 "); note.hidden = true; const reveal = button("Reveal：实际范围"); reveal.addEventListener("click", () => { answer.hidden = false; note.hidden = false; }); rootElement.append(node("p", "lesson10-prompt", "降价额不能为负，且单件利润不能为负。数学答案还要符合实际。"), reveal, answer, note); }
function renderLab(rootElement, cleanup) { let discount = 0; const item = model(DATA, discount); const panel = node("div", "lesson10-workbench"); const range = document.createElement("input"); range.type = "range"; range.min = "0"; range.max = "20"; range.step = "1"; range.value = "0"; range.dataset.lesson10Discount = ""; range.setAttribute("aria-label", "降价 d（元）"); const value = node("output", "lesson10-value", "0"); const readout = node("p", "lesson10-status"); readout.dataset.lesson10ProfitReadout = ""; const current = formula(latexFor(item), "利润函数", "lesson10-formula lesson10-current"); const graphHost = node("div"); let chart;
  function update() { const next = model(DATA, discount); value.textContent = String(discount); current.replaceChildren(); renderFormula(current, latexFor(next), { displayMode: true, ariaLabel: "利润函数" }); readout.textContent = "降价 " + discount + " 元：单件利润 " + (30 - discount) + " 元；日销量 " + (40 + 2 * discount) + " 件；日利润 " + next.profit + " 元。"; chart.update({ points: [{ x: discount, y: next.profit / 100, color: "#d98935", radius: 6 }] }); }
  const controls = node("div", "lesson10-range"); controls.append(node("label", "", "降价 d（元）"), range, value); panel.append(node("p", "lesson10-prompt", "拖动降价额 d，观察公式、图象与实际意义同步变化。图象纵轴以百元计。"), controls, current, readout); const layout = node("div", "lesson10-layout"); const graphPanel = node("div", "lesson10-graph-panel"); graphHost.className = "lesson10-graph-host"; graphPanel.append(graphHost); layout.append(graphPanel, panel); rootElement.append(layout); chart = graph(graphHost, item, { x: 0, y: item.profit }); range.addEventListener("input", () => { discount = Number(range.value); update(); }); cleanup.push(() => chart.destroy()); update(); }
function renderCheckpoint(rootElement) { const answer = node("p", "lesson10-reveal", "令 P(d)=1200，解得 d=0 或 d=10。原价销售与降价 10 元都能达到 1200 元日利润。 "); answer.hidden = true; const reveal = button("Reveal：解目标利润方程"); reveal.addEventListener("click", () => { answer.hidden = false; }); rootElement.append(node("p", "lesson10-prompt", "达到 1200 元利润，有几种降价方案？这是抛物线与水平线 P=1200 的交点问题。"), reveal, answer); }
function renderPractice(rootElement, random) { let index = Math.min(PRACTICE.length - 1, Math.floor(Math.max(0, Math.min(.999, Number(random()) || 0)) * PRACTICE.length)); const prompt = node("p", "lesson10-question"); const answer = node("div", "lesson10-reveal"); answer.dataset.lesson10PracticeAnswer = ""; const reveal = button("Reveal：检查答案"); reveal.dataset.lesson10RevealPractice = ""; const next = button("New Practice", "lesson10-action lesson10-secondary"); function render() { const data = PRACTICE[index]; const item = model(data); prompt.textContent = "原售价 " + data.price + " 元，进价 " + data.cost + " 元；每天售 " + data.sales + " 件。每降价 1 元多售 " + data.gain + " 件。求最大日利润。"; answer.replaceChildren(formula(latexFor(item), "利润函数"), node("p", "", "顶点对应 d=" + item.best.toFixed(2) + "，最大利润为 " + item.maximum.toFixed(2) + " 元。")); answer.hidden = true; } reveal.addEventListener("click", () => { answer.hidden = false; }); next.addEventListener("click", () => { index = (index + 1) % PRACTICE.length; render(); }); rootElement.append(node("p", "lesson10-prompt", "每次生成一组商品数据。先写利润函数，再求最大利润；答案默认隐藏。"), prompt, node("div", "lesson10-actions")); rootElement.querySelector(".lesson10-actions").append(next, reveal); rootElement.append(answer); render(); }

const RENDERERS = [renderOpening, renderRelations, renderBuild, renderMaximum, renderDomain, renderLab, renderCheckpoint, renderPractice];
export function renderLesson10(stage, { step = 1, onStepChange = () => {}, random = Math.random } = {}) { const safe = Math.min(8, Math.max(1, Number(step) || 1)); const cleanup = []; const item = root(safe); if (safe === 8) renderPractice(item, random); else RENDERERS[safe - 1](item, cleanup); navigation(item, safe, onStepChange); stage.replaceChildren(item); return { destroy() { cleanup.forEach((dispose) => dispose()); } }; }
